/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/sections/AboutMe.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    Contact: typeof import('./src/components/sections/Contact.vue')['default']
    ContactLinks: typeof import('./src/components/ContactLinks.vue')['default']
    Intro: typeof import('./src/components/sections/Intro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/sections/Skills.vue')['default']
    Work: typeof import('./src/components/sections/Work.vue')['default']
  }
}
